Calculators dynamic CTA v2
inBeat/inbeat-website pull request #173
Opened 2022-06-30 18:41 UTC by BashCloud

2022-07-01 16:50 UTC, Genoux requested changes

2022-07-02 14:55 UTC, BashCloud commented on themes/inbeat/layouts/partials/site/emailCaptureMixin.html
> +                    request.addEventListener('loadend', (() => {
Nice catch, I wasn't able to test this particular method.

Thanks.

2022-07-04 03:03 UTC, Genoux submitted a review, later dismissed

2022-07-04 03:03 UTC, Genoux commented on themes/inbeat/layouts/partials/site/emailCaptureMixin.html
> +                    request.addEventListener('loadend', (() => {
the `request` is not in the function scope, so it's still not defined - if you pass the request variable to that function, it should work

2022-07-04 09:11 UTC, mgufrone approved these changes

2022-07-04 14:51 UTC, merged